# Practicando lo aprendido hasta ahora

In [2]:
# Import libraries
import numpy as np
import pandas as pd

In [3]:
# UpLoad data
df = pd.read_csv('../data/train_and_test2.csv')

In [4]:
# Data info
df.shape # rows, columns

(1309, 28)

In [5]:
# Data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [6]:
df.iloc[:10,:] # index, columns
print(df.iloc[:0,6:27])

Empty DataFrame
Columns: [zero.1, zero.2, zero.3, zero.4, zero.5, zero.6, Parch, zero.7, zero.8, zero.9, zero.10, zero.11, zero.12, zero.13, zero.14, Pclass, zero.15, zero.16, Embarked, zero.17, zero.18]
Index: []

[0 rows x 21 columns]


In [7]:
a = df.iloc[:0,6:27]
j = 1
list_z = []
for i in a:
    # print(i)
    # print(j)
    if i == f'zero.{j}':
        list_z.append(i)
        j += 1
list_z

['zero.1',
 'zero.2',
 'zero.3',
 'zero.4',
 'zero.5',
 'zero.6',
 'zero.7',
 'zero.8',
 'zero.9',
 'zero.10',
 'zero.11',
 'zero.12',
 'zero.13',
 'zero.14',
 'zero.15',
 'zero.16',
 'zero.17',
 'zero.18']

In [8]:
df_update = df.drop(list_z, axis=1)
df_update = df_update.drop('zero', axis=1)
df_id_age = df_update.loc[:,['Passengerid', 'Age']]
df_id_age

Passengerid   Age
0               1  22.0
1               2  38.0
2               3  26.0
3               4  35.0
4               5  35.0
...           ...   ...
1304         1305  28.0
1305         1306  39.0
1306         1307  38.5
1307         1308  28.0
1308         1309  28.0

[1309 rows x 2 columns]

In [9]:
df_age = df_update['Age']
df_sex = df_update['Sex']

male = df_update[df_sex == 1]
female = df_update[df_sex == 0]

male_under_18 = male[df_age < 18]
male_under_18 = male_under_18.reset_index(drop=True)
male_under_18

# male_up_18 = male[df_age >= 18]
# female_under_18 = female[df_age < 18]
# female_up_18 = female[df_age >= 18]

C:\Users\kenyi\AppData\Local\Temp\ipykernel_10344\3517565909.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  male_under_18 = male[df_age < 18]


Passengerid    Age     Fare  Sex  sibsp  Parch  Pclass  Embarked  2urvived
0            10  14.00  30.0708    1      1      0       2       0.0         1
1            11   4.00  16.7000    1      1      1       3       2.0         1
2            15  14.00   7.8542    1      0      0       3       2.0         0
3            23  15.00   8.0292    1      0      0       3       1.0         1
4            25   8.00  21.0750    1      3      1       3       2.0         0
..          ...    ...      ...  ...    ...    ...     ...       ...       ...
67         1207  17.00   7.7333    1      0      0       3       1.0         0
68         1218  12.00  39.0000    1      2      1       2       2.0         0
69         1237  16.00   7.6500    1      0      0       3       2.0         0
70         1246   0.17  20.5750    1      1      2       3       2.0         0
71         1301   3.00  13.7750    1      1      1       3       2.0         0

[72 rows x 9 columns]

In [10]:
ages = df_age
print(f"Total de pasajeros: {len(ages)}")
print(f"Total de pasajeros menores de 18: {len(ages[ages < 18])}")
print(f"Total de pasajeros mayores de 18: {len(ages[ages > 18])}")
print(f"Total de pasajeros mayores de 60: {len(ages[ages > 60])}")
print(f"Total de varones {len(df_sex[df_sex == 1])}")
print(f"Total varones mayores de 18 años: {len(male_up_18)}")
print(f"Total varones menores de 18 años: {len(male_under_18)}")
print(f"Total de mujeres {len(df_sex[df_sex == 0])}")
print(f"Total mujeres mayores de 18 años: {len(female_up_18)}")
print(f"Total mujeres menores de 18 años: {len(female_under_18)}")
print(f"Promedio de edad: {round(ages.mean(), 2)}")
print(f"Mediana: {ages.median()}")
print(f"Máxima edad: {ages.max()}")
print(f"Mínima edad: {ages.min()}")


Total de pasajeros: 1309
Total de pasajeros menores de 18: 154
Total de pasajeros mayores de 18: 1116
Total de pasajeros mayores de 60: 33
Total de varones 466


NameError: name 'male_up_18' is not defined

In [ ]:
df

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [ ]:
l = [i for i in a]
len(l)
print(len(l))
for i in l:
    for j in range(len(l)):
        if i == f'zero.{j}':
            print(i)

21
zero.1
zero.2
zero.3
zero.4
zero.5
zero.6
zero.7
zero.8
zero.9
zero.10
zero.11
zero.12
zero.13
zero.14
zero.15
zero.16
zero.17
zero.18


In [14]:
df.loc[0:10, :]

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0             1  22.0   7.2500    0      1     0       0       0       0   
1             2  38.0  71.2833    1      1     0       0       0       0   
2             3  26.0   7.9250    1      0     0       0       0       0   
3             4  35.0  53.1000    1      1     0       0       0       0   
4             5  35.0   8.0500    0      0     0       0       0       0   
5             6  28.0   8.4583    0      0     0       0       0       0   
6             7  54.0  51.8625    0      0     0       0       0       0   
7             8   2.0  21.0750    0      3     0       0       0       0   
8             9  27.0  11.1333    1      0     0       0       0       0   
9            10  14.0  30.0708    1      1     0       0       0       0   
10           11   4.0  16.7000    1      1     0       0       0       0   

    zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0        0  ...        0        0        0       3        0        0   
1        0  ...        0        0        0       1        0        0   
2        0  ...        0        0        0       3        0        0   
3        0  ...        0        0        0       1        0        0   
4        0  ...        0        0        0       3        0        0   
5        0  ...        0        0        0       3        0        0   
6        0  ...        0        0        0       1        0        0   
7        0  ...        0        0        0       3        0        0   
8        0  ...        0        0        0       3        0        0   
9        0  ...        0        0        0       2        0        0   
10       0  ...        0        0        0       3        0        0   

    Embarked  zero.17  zero.18  2urvived  
0        2.0        0        0         0  
1        0.0        0        0         1  
2        2.0        0        0         1  
3        2.0        0        0         1  
4        2.0        0        0         0  
5        1.0        0        0         0  
6        2.0        0        0         0  
7        2.0        0        0         0  
8        2.0        0        0         1  
9        0.0        0        0         1  
10       2.0        0        0         1  

[11 rows x 28 columns]

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
df.tail()

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[5 rows x 28 columns]

In [24]:
arr = np.array([13,6,3,5,10])

In [26]:
np.linspace(0,10,2)

array([ 0., 10.])

In [23]:
np.argmax(arr)
np.sort(arr)

array([ 3,  5,  6, 10, 13])