# Curso de Manipulación y Transformaciones de Datos con Pandas y Numpy

In [1]:
import pandas as pd
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz

matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Accedemos a columnas dentro de una matriz

In [5]:
matriz[0, 2]

3

### Accedemos a mas de un objeto

In [6]:
arr[0:3]

array([1, 2, 3])

In [7]:
arr[::3]

array([1, 4, 7])

In [8]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[-3:]

array([7, 8, 9])

In [9]:
# Matriz
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])