# Condiciones

In [2]:
import numpy as np

In [3]:
# Generamos nuestro array

arr = np.linspace(0, 10, 10, dtype='int8')
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10], dtype=int8)

In [4]:
# Comprobamos en el array cuales son lso valores mayores a 5

index_con = arr > 5
index_con

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [7]:
arr[index_con] # Nos devuelve los valores mayores a 5

array([ 6,  7,  8, 10], dtype=int8)

In [9]:
# Valores entre 5 y 9
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [11]:
# Modificamos valores que cumplan una condicion
arr[arr > 5] = 100
arr

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100], dtype=int8)