# Condiciones

In [2]:
import numpy as np

In [5]:
# Generamos nuestro array

arr = np.linspace(0, 10, 10, dtype='int8')
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10], dtype=int8)

In [9]:
# Comprobamos en el array cuales son lso valores mayores a 5

index_con = arr > 5
index_con

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
arr[index_con] # Nos devuelve los valores mayores a 5

array([ 6,  7,  8, 10], dtype=int8)