# Copy

In [3]:
import numpy as np

In [4]:
# Generamos nuestro array

arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Trozamos el array

trozo_arr = arr[0:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
# Covertimos los datos extraidos en 0s
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

In [15]:
# Verificamos que los datos fueron modificados
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

### Copy
- Con .copy() creamos una copia para no dañar nuestro array original
- Esta función te ayudará a prevenir muchos errores y tener más confianza a la hora de manipular los datos

In [17]:
# Copiamos el array
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [20]:
# Modificamos el array original
arr_copy[:] = 0
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# Verificamos que los datos de la variable padre no fueron modificados
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])