# Creación de arrays con Numpy

In [1]:
import numpy as np

In [2]:
# Una lista con Python
py_ist = list(range(1, 10))
np_arr = np.arange(1, 10)
print(np_arr)

[1 2 3 4 5 6 7 8 9]


In [3]:
# Lista de Numpy con steps

np_arr = np.arange(0, 10, 2)
print(np_arr)

[0 2 4 6 8]


In [4]:
# Vector de numpy con 0
v_zeros = np.zeros(10)
print(v_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Matrzi de Numpy con 0
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Vector de Numpy con 1
v_ones = np.ones(10)
print(v_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
# Matriz de Numpy con 1
m_ones = np.ones((3, 3))
print(m_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Vector de Numpy con valores aleatorios
v_rand = np.random.rand(10)
print(v_rand)

[0.73032747 0.92296014 0.85438877 0.6983029  0.08185497 0.51388966
 0.82709754 0.05688627 0.37056804 0.83855563]


In [9]:
# Matriz de Numpy con valores aleatorios
m_rand = np.random.rand(3, 3)
print(m_rand)

[[0.07203538 0.84172915 0.31757249]
 [0.09132244 0.52772448 0.14513568]
 [0.51931938 0.78734697 0.57457003]]


In [10]:
# Linspace de Numpy
# 10 valores entre 0 y 10 (incluyendo 0 y 10) y 100 valores en total
v_linspace = np.linspace(0, 10, 100)
print(v_linspace)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [11]:
# Matriz de Numpy con eye
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Matrzi con valor aleatorio entre 0 y 1
v_rand = np.random.rand(4, 4)
print(v_rand)

[[0.85073738 0.44438903 0.03315958 0.44364617]
 [0.41020648 0.72253563 0.37867246 0.39675851]
 [0.88756223 0.18115526 0.85394438 0.88655195]
 [0.79687713 0.28484985 0.55431774 0.7556247 ]]


In [19]:
# Valor aleatorio
# 1 y 10 son los valores mínimo y máximo del rango de valores aleatorios a generar (1, 10) y 100 valores en total (100 valores aleatorios)
v_rand = np.random.randint(1, 10, 100)
print(v_rand)

[2 7 9 5 9 4 7 8 6 8 7 9 3 6 6 4 4 5 4 9 4 2 8 4 5 3 7 8 3 5 5 1 3 5 4 8 4
 3 1 6 9 6 1 1 2 1 1 2 1 5 9 4 8 8 4 9 3 2 9 6 3 1 9 5 5 3 7 9 1 2 5 8 3 8
 2 2 2 3 2 4 4 6 3 8 6 5 4 2 4 1 2 9 5 9 4 8 6 3 3 1]
