# Dimensiones en Numpy

### Scalar : Array de un solo elemento
### Vector : Array de más de un elemento y una dimensión
### Matrix : Array de más de un elemnto y 2 dimendiones
### Tensor : Array de más de un elemento y más de 3 dimensiones

In [3]:
import numpy as np

In [7]:
# Scalar
scalar = np.array(43)
print(scalar)
scalar.ndim

43


0

In [9]:
# Vector
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [11]:
# Matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]]


2

In [12]:
# Tensor
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

## Agregar y eliminar  dimensiones

In [21]:
# Agregamos 10 dimensiones
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [26]:
# Expandimos el vector en la dimensión 0
vector = np.array([1, 2, 3])
print(vector)
vector = np.expand_dims(vector, axis=0)
print(vector)
vector.ndim


# Expandimos el vector en la dimensión 1
vector = np.array([1, 2, 3])
print(vector)
vector = np.expand_dims(vector, axis=1)
print(vector)
vector.ndim


[1 2 3]
[[1 2 3]]
[1 2 3]
[[1]
 [2]
 [3]]


2

In [28]:
# Eliminar dimensiones que no sean necesarias
vector = np.array([1, 2, 3], ndmin=10)
print(vector, vector.ndim)
vector = np.squeeze(vector)
print(vector, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Reto
- Definir un tensor de 5 dimensiones
- Sumar una dimensión en algún eje
- Borrar dimensiones que no se usen

In [30]:
new_vector = np.array([[[[[1,2,3]]]]])
print(new_vector, new_vector.ndim)

[[[[[1 2 3]]]]] 5


In [33]:
new_vector = np.expand_dims(new_vector, axis=0)
print(new_vector, new_vector.ndim)

[[[[[[[1 2 3]]]]]]] 7


In [34]:
new_vector = np.squeeze(new_vector)
print(new_vector, new_vector.ndim)

[1 2 3] 1
