# Funciones principales

In [107]:
import numpy as np

In [108]:
# Generamos un array

arr = np.random.randint(1, 10, 20)
matriz = arr.reshape(4, 5)
matriz

array([[6, 2, 3, 4, 1],
       [6, 3, 7, 4, 6],
       [9, 8, 5, 4, 7],
       [3, 1, 7, 5, 8]])

In [109]:
# Valor maximo en un vector
arr.max()

9

In [110]:
# Valor máximo y minimo en una matriz
val_max = matriz.max()
val_min = matriz.min()
print("Valor máximo en la matriz: ", val_max)
print("Valor mínimo en la matriz: ", val_min)

Valor máximo en la matriz:  9
Valor mínimo en la matriz:  1


In [111]:
# Valor máximo en una matriz en una columna
col_max = matriz.max(axis=0)
col_min = matriz.min(axis=0)
print("Valor máximo en la columna: ", col_max)
print("Valor mínimo en la columna: ", col_min)

Valor máximo en la columna:  [9 8 7 5 8]
Valor mínimo en la columna:  [3 1 3 4 1]


In [112]:
# Valor máximo en una matriz en una fila
f_max = matriz.max(axis=1)
f_min = matriz.min(axis=1)
print("Valor máximo en la fila: ", f_max)
print("Valor mínimo en la fila: ", f_min)

Valor máximo en la fila:  [6 7 9 8]
Valor mínimo en la fila:  [1 3 4 1]


In [113]:
# Argmax y argmin en un vector
amx_arr = arr.argmax()
amn_arr = arr.argmin()
print("Argmax: ", amx_arr)
print("Argmin: ", amn_arr)
print("Vector: ", arr)

Argmax:  10
Argmin:  4
Vector:  [6 2 3 4 1 6 3 7 4 6 9 8 5 4 7 3 1 7 5 8]


#### Argmax y Argmin en matrices

In [114]:
# Argmax y argmin toda la matriz
amx_matriz = matriz.argmax()
amn_matriz = matriz.argmin()
print("Argmax: ", amx_matriz)
print("Argmin: ", amn_matriz)
print("Matriz: \n", matriz)

Argmax:  10
Argmin:  4
Matriz: 
 [[6 2 3 4 1]
 [6 3 7 4 6]
 [9 8 5 4 7]
 [3 1 7 5 8]]


In [115]:
# En la dimension 0
amx_matriz = matriz.argmax(axis=0)
amn_matriz = matriz.argmin(axis=0)
print("Argmax: ", amx_matriz)
print("Argmin: ", amn_matriz)
print("Matriz: \n", matriz)

Argmax:  [2 2 1 3 3]
Argmin:  [3 3 0 0 0]
Matriz: 
 [[6 2 3 4 1]
 [6 3 7 4 6]
 [9 8 5 4 7]
 [3 1 7 5 8]]


In [116]:
# En la dimension 1
amx_matriz = matriz.argmax(axis=1)
amn_matriz = matriz.argmin(axis=1)
print("Argmax: ", amx_matriz)
print("Argmin: ", amn_matriz)
print("Matriz: \n", matriz)

Argmax:  [0 2 0 4]
Argmin:  [4 1 3 1]
Matriz: 
 [[6 2 3 4 1]
 [6 3 7 4 6]
 [9 8 5 4 7]
 [3 1 7 5 8]]


#### Distancia entre el valor más bajo con el más alto

In [117]:
# pic to pic 

ptp_arr = arr.ptp()
ptp_matriz = matriz.ptp(axis=0)
print("Ptp array: ", ptp_arr)
print("Ptp matriz: ", ptp_matriz)


Ptp array:  8
Ptp matriz:  [6 7 4 1 7]


# Funciones Estadisticas

In [118]:
# Generamos nuestro Array

new_arr = np.random.randint(1, 20, 20)
new_mat =  new_arr.reshape(5, 4)

print("Nueva Matriz: \n", new_mat)

Nueva Matriz: 
 [[ 2  4 17  4]
 [ 7 10  7  7]
 [14 10  3 14]
 [ 8 18 17 18]
 [ 4 11 12 14]]


In [119]:
per_arr = np.percentile(new_arr, 50)

print("Array: ", new_arr)
print("Percentil: ", per_arr)

Array:  [ 2  4 17  4  7 10  7  7 14 10  3 14  8 18 17 18  4 11 12 14]
Percentil:  10.0


In [120]:
# Ordenamos el array con ola funcion sort

new_arr.sort()
print("Array ordenado: ", new_arr)

Array ordenado:  [ 2  3  4  4  4  7  7  7  8 10 10 11 12 14 14 14 17 17 18 18]


In [121]:
# Mediana
med_arr = np.median(new_arr)
print("Mediana: ", med_arr)

Mediana:  10.0


In [122]:
# Media
media_arr = np.mean(new_arr)
print("Media: ", media_arr)

Media:  10.05


In [123]:
# Desviación estándar
std_arr = np.std(new_arr)
print("Desviación estándar: ", std_arr)

Desviación estándar:  5.152426612771889


In [124]:
# Varianza
var_arr = np.var(new_arr)
print("Varianza: ", var_arr)

Varianza:  26.547500000000003


In [129]:
# Concatenación de arrays

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])