# Operaciones

In [1]:
import numpy as np

In [3]:
# Generamos una lista de Python
lista = [1, 2, 3, 4, 5]

In [6]:
# Intentamos multioplicar valores a la lista
lista * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

### Numpy acepta operaciones dentro de sus arrayas

In [8]:
# Generamos nuestro array y generamos un a copia de esta
arr = np.arange(10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Multiplicamos el array por 2

arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Sumamos el array con el array2
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# Restamos el array con el array2
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# Multiplicamos el array con el array2
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
# Dividimos el array con el array2
arr / arr2

C:\Users\kenyi\AppData\Local\Temp\ipykernel_4880\1481473842.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
# Potenciamos el array con el array2
arr ** arr2

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

### Operaciones en Matrices

In [22]:
# Generamos una matriz a partir de un array y guardamos una copia
matriz = arr.reshape(2, 5)
matriz2 = matriz.copy()

In [24]:
# Sumamos la matriz con la matriz2
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [26]:
# Restamos la matriz con la matriz2
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
# Multiplicamos la matriz con la matriz2
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [28]:
# Dividimos la matriz con la matriz2
matriz / matriz2

C:\Users\kenyi\AppData\Local\Temp\ipykernel_4880\2393006883.py:2: RuntimeWarning: invalid value encountered in divide
  matriz / matriz2


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [29]:
# Potenciamos la matriz con la matriz2
matriz ** matriz2

array([[        1,         1,         4,        27,       256],
       [     3125,     46656,    823543,  16777216, 387420489]])

In [32]:
# Producto punto
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])