In [2]:
import numpy as np

In [35]:
# Generamos un array
arr = np.random.randint(0, 10, size=(3, 2))
arr

array([[8, 9],
       [0, 2],
       [9, 6]])

In [8]:
# Shape, sirve para ver el tamaño de un array

arr.shape

(3, 2)

In [33]:
# Reshape, sirve para cambiar el tamaño de un array

arr.reshape(2, 3)

array([[4, 7, 4],
       [7, 9, 7]])

In [24]:
# Otra forma de usar reshape

np.reshape(arr, (2, 3))

array([[4, 7, 4],
       [7, 9, 7]])

In [36]:
# Como esta ordenando nuestros datos en el array

arr

array([[8, 9],
       [0, 2],
       [9, 6]])

In [37]:
# Se puede hacer un reshape como lo haría C
np.reshape(arr, (2, 3), 'C')

array([[8, 9, 0],
       [2, 9, 6]])

In [39]:
# Se puede hacer un reshape como lo haría Fortran
np.reshape(arr, (2, 3), 'F')

array([[8, 9, 2],
       [0, 9, 6]])

In [40]:
# Reshape segun como este optimizando nuestro PC
np.reshape(arr, (2, 3), 'A')

array([[8, 9, 0],
       [2, 9, 6]])

## Reto
- Crear un array de cualquier dimensión y cambiar sus dimensiones.
- Intenta cambiar el array de forma que no respete la estructura original

In [46]:
new_arr = np.random.randint(0, 10, (5, 4))
new_arr

array([[5, 1, 0, 9],
       [4, 4, 7, 0],
       [5, 3, 0, 5],
       [8, 8, 2, 5],
       [3, 8, 1, 0]])

#### Verificamos las dimensiones y las modificacmos

In [48]:
# Verificamos el tamaño de nuestro array

new_arr.shape


(5, 4)

In [51]:
# Cambiamos el tamaño de nuestro array

new_arr.reshape(10, 2)

array([[5, 1],
       [0, 9],
       [4, 4],
       [7, 0],
       [5, 3],
       [0, 5],
       [8, 8],
       [2, 5],
       [3, 8],
       [1, 0]])